# -*- coding: utf-8 -*-
"""
Created on Tue Aug 22 15:31:49 2017

@author: Bodhisatwa
"""

LANG=["Hindi","English","Marathi","Bengali","Punjabi","Oriya","Gujrati","Assamesse","Tamil","Malayalam","Telugu",
      "German",
      "Spanish",
      "French"]

P_LANG=["4th Dimension/4D",
"ABAP",
"ABC",
"ActionScript",
"Ada",
"Agilent VEE",
"Algol",
"Alice",
"Angelscript",
"Apex",
"APL",
"AppleScript",
"Arc",
"Arduino",
"ASP",
"AspectJ",
"Assembly",
"ATLAS",
"Augeas",
"AutoHotkey",
"AutoIt",
"AutoLISP",
"Automator",
"Avenue",
"Awk",
"Bash",
"Basic",
"bc",
"BCPL",
"BETA",
"BlitzMax",
"Boo",
"Bourne Shell",
"Bro",
"C",
"C Shell",
"C#",
"C++",
"CLI",
"C-Omega",
"Caml",
"Ceylon",
"CFML",
"cg",
"Ch",
"CHILL",
"CIL",
"CL (OS/400)",
"Clarion",
"Clean",
"Clipper",
"Clojure",
"CLU",
"COBOL",
"Cobra",
"CoffeeScript",
"ColdFusion",
"COMAL",
"Lisp",
"Coq",
"cT",
"Curl",
"Dart",
"DCL",
"DCPU-16 ASM",
"Delphi",
"Object Pascal",
"DiBOL",
"Dylan",
"eC",
"Ecl",
"ECMAScript",
"EGL",
"Eiffel",
"Elixir",
"Emacs Lisp",
"Erlang",
"Etoys",
"Euphoria",
"EXEC",
"F#",
"Factor",
"Falcon",
"Fancy",
"Fantom",
"Felix",
"Forth",
"Fortran",
"Fortress",
"FoxPro",
"Gambas",
"GNU Octave",
"Go",
"Google AppsScript",
"Gosu",
"Groovy",
"Haskell",
"haXe",
"Heron",
"HPL",
"HyperTalk",
"Icon",
"IDL",
"Inform",
"Informix-4GL",
"INTERCAL",
"Io",
"Ioke",
"J#",
"JADE",
"Java",
"Java FX Script",
"JavaScript",
"JScript",
"JScript.NET",
"Julia",
"Korn Shell",
"Kotlin",
"LabVIEW",
"Ladder Logic"
"Lasso",
"Limbo",
"Lingo",
"Lisp",
"Logo",
"Logtalk",
"LotusScript",
"LPC",
"Lua",
"Lustre",
"M4",
"MAD",
"Magic",
"Magik",
"Malbolge",
"MANTIS",
"Maple",
"Mathematica",
"MATLAB",
"Max/MSP",
"MAXScript",
"MEL",
"Mercury",
"Mirah",
"Miva",
"ML",
"Monkey",
"Modula-2",
"Modula-3",
"MOO",
"Moto",
"MS-DOS",
"MUMPS",
"NATURAL",
"Nemerle",
"Nimrod",
"NQC",
"NSIS",
"Nu",
"NXT-G",
"Oberon",
"Object Rexx",
"Objective-J",
"OCaml",
"Occam",
"ooc",
"Opa",
"OpenCL",
"OpenEdge ABL",
"OPL",
"Oz",
"Paradox",
"Parrot",
"Pascal",
"Perl",
"PHP",
"Pike",
"PILOT",
"PL/I",
"PL"
"SQL",
"Pliant",
"PostScript",
"POV-Ray",
"PowerBasic",
"PowerScript",
"PowerShell",
"Processing",
"Prolog",
"Puppet",
"Pure Data",
"Python",
"R",
"Racket",
"REALBasic",
"REBOL",
"Revolution",
"REXX",
"RPG (OS/400)",
"Ruby",
"Rust",
"S-PLUS",
"SAS",
"Sather",
"Scala",
"Scheme",
"Scilab",
"Scratch",
"sed",
"Seed7",
"Self",
"Shell",
"SIGNAL",
"Simula",
"Simulink",
"Slate",
"Smalltalk",
"Smarty",
"SPARK",
"SPSS",
"SQR",
"Squeak",
"Squirrel",
"Standard ML",
"Suneido",
"TACL",
"Tcl",
"Tex",
"thinBasic",
"TOM",
"Transact-SQL",
"Turing",
"TypeScript",
"Vala/Genie",
"VBScript",
"VBA",
"Verilog",
"VHDL",
"VimL",
".NET",
"WebDNA",
"Whitespace",
"X10",
"xBase"
"XBase++",
"Xen",
"XPL",
"XSLT",
"XQuery",
"yacc",
"Yorick",
"Z shell"] 

skills=["Strategic Sourcing", "Leadership Hiring", "Global Mobility","Manpower Planning", "Bulk hiring","Talent assessment", "Vendor management", "Team management", "Employer Branding","BUSINESS DEVELOPMENT","PROJECT MANAGEMENT",'Demand Generation','Financial Modeling','Risk Management','Strategic Planning','Key Stakeholder Management','Market Research','Product Development','Strategy Consulting','Supply Chain management','Content Development','Behavioural Training','Business Strategy','Marketing Strategy',
       'Content Management',
       'Performance Management',
       'Standardized Content',
       'Organizational Development',
       'Data Analysis',
       'Employee Engagement',
       'program design',
       'eLearning',
       'training delivery']   

roles=['ENGINEERING CONSULTANCY','TECHNICAL ADVISORY','PROCUREMENT ASSISTANCE','THROUGHPUT MANAGEMENT']

roles_2=['ENSURING',
         'HANDLED',
         'ENSURING',
         'VERIFYING',
         'MONITORED',
         'MAINTAINING',
         'MANAGING',
         'IMPROVEMENT']

soft=['Team Player',
'Innovativeness',
'Attention',
'Perseverance',
'Team Engagement',
'Leadership',
'Strategic Communications',
'Reading',
'Writing',
'Baking',
]  